### ISSUE TITLE
pyrax.set_credentials failure

### ISSUE THREAD

**Issue by ghost** [pycontribs/pyrax#115]
We're using version 1.4.5.

We called pyrax.set_credentials with good credentials. Pyrax decided that we needed to authenticate before we needed to authenticate. :-(

Is this the known swiftclient bug? Or another problem?

Here's the tail end of the stack trace:

```
Traceback (most recent call last):

[snip]

 File "/usr/local/lib/python2.7/dist-packages/ips_quisitor/common/cloud.py", line 55, in _connection
   pyrax.set_credentials(settings.CF_DS_ACCT, settings.CF_DS_API)

 File "/usr/local/lib/python2.7/dist-packages/pyrax/__init__.py", line 347, in _wrapped
   return fnc(*args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/pyrax/__init__.py", line 384, in set_credentials
   _auth_and_connect(region=region)

 File "/usr/local/lib/python2.7/dist-packages/pyrax/__init__.py", line 462, in _auth_and_connect
   connect_to_services(region=region)

 File "/usr/local/lib/python2.7/dist-packages/pyrax/__init__.py", line 515, in connect_to_services
   cloudservers = connect_to_cloudservers(region=region)

 File "/usr/local/lib/python2.7/dist-packages/pyrax/__init__.py", line 347, in _wrapped
   return fnc(*args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/pyrax/__init__.py", line 358, in _wrapped
   raise exc.NotAuthenticated(msg)

NotAuthenticated: Authentication required before calling 'connect_to_cloudservers'.
```

**Comment by thijstriemstra** [comment]
I'm running into a different `NotAuthenticated` exception with pyrax 1.9.7:

```
 File "/home/bar/virtualenvs/foo/lib/python2.7/site-packages/pyrax/__init__.py", line 739, in connect_to_cloudfiles
   public=is_public)
 File "/home/bar/virtualenvs/foo/lib/python2.7/site-packages/pyrax/__init__.py", line 439, in _wrapped
   return fnc(*args, **kwargs)
 File "/home/bar/virtualenvs/foo/lib/python2.7/site-packages/pyrax/__init__.py", line 450, in _wrapped
   raise exc.NotAuthenticated(msg)
NotAuthenticated: Authentication required before calling '_create_client'.
``` 
but this is triggered from django-cumulus so I'll look there first.
