### ISSUE TITLE
Installation error: [Exception: Versioning for this project requires...]

### ISSUE THREAD

**Issue by johnmrobinson** [pycontribs/pyrax#450]
I installed for python 2.7 on OS X using both 
(1) the standard pip install pyrax and 
(2) the git version.

Both ways, I receive the following error:

Suggestions would be helpul.
Thanks,
~John

```
>>> import pyrax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pyrax/__init__.py", line 51, in <module>
    from .identity import *
  File "/Library/Python/2.7/site-packages/pyrax/identity/keystone_identity.py", line 7, in <module>
    from ..base_identity import BaseIdentity
  File "/Library/Python/2.7/site-packages/pyrax/base_identity.py", line 20, in <module>
    from pyrax import exceptions as exc
  File "/Library/Python/2.7/site-packages/pyrax/exceptions.py", line 22, in <module>
    from novaclient import exceptions as _nova_exceptions
  File "/Library/Python/2.7/site-packages/novaclient/__init__.py", line 18, in <module>
    __version__ = pbr.version.VersionInfo('python-novaclient').version_string()
  File "/Library/Python/2.7/site-packages/pbr/version.py", line 78, in version_string
    for part in self.release_string().split('.'):
  File "/Library/Python/2.7/site-packages/pbr/version.py", line 70, in release_string
    self.release = self._get_version_from_pkg_resources()
  File "/Library/Python/2.7/site-packages/pbr/version.py", line 62, in _get_version_from_pkg_resources
    return packaging.get_version(self.package)
  File "/Library/Python/2.7/site-packages/pbr/packaging.py", line 870, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
```

**Comment by ncit-cluster** [comment]
:+1: pip install --upgrade distribute works

**Comment by chauhanhardik** [comment]
After completing all this process, I was unable to fix the same issue

this is error log :- 

ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/dashboard-analytics/local/lib/python2.7/site-packages/pbr/core.py", line 104, in pbr
    attrs = util.cfg_to_args(path)
  File "/home/vagrant/.virtualenvs/dashboard-analytics/local/lib/python2.7/site-packages/pbr/util.py", line 238, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/vagrant/.virtualenvs/dashboard-analytics/local/lib/python2.7/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/vagrant/.virtualenvs/dashboard-analytics/local/lib/python2.7/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/vagrant/.virtualenvs/dashboard-analytics/local/lib/python2.7/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/home/vagrant/.virtualenvs/dashboard-analytics/local/lib/python2.7/site-packages/pbr/packaging.py", line 673, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
error in setup command: Error parsing /edx/app/edxapp/edx-analytics/edx-analytics-pipeline/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
make: *** [develop] Error 1

**Comment by jiaqingw** [comment]
:+1: pip install --upgrade distribute works

**Comment by cchriste** [comment]
@eljrax pip install --upgrade distribute works!

**Comment by alexlin88** [comment]
pip install --upgrade distribute works!

**Comment by tameek** [comment]
$ sudo pip install --upgrade distribute works for me as well!

**Comment by XieXianbin** [comment]
sudo pip install --upgrade works for me, tks

**Comment by JAYANDJEAN** [comment]
I download distribute in https://pypi.python.org/pypi/distribute/0.7.3.anyway,thanks.

**Comment by JAYANDJEAN** [comment]
I download distribute in https://pypi.python.org/pypi/distribute/0.7.3   anyway,thanks.

**Comment by dduuch** [comment]
I have the same error, but fix was.... just install git package :)
