### ISSUE TITLE
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'SplitResult'

### ISSUE THREAD

**Issue by jribbens** [pycontribs/pyrax#514]
The above error is what you get when doing 'import pyrax'. This is because setup.py incorrectly says that pyrax needs 'six' version 1.5.2, when in fact it needs a newer version than that. I think it might need 1.6. 1.8 definitely works.

```
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyrax/__init__.py", line 59, in <module>
    from novaclient.shell import OpenStackComputeShell as _cs_shell
  File "/usr/local/lib/python2.7/dist-packages/novaclient/shell.py", line 47, in <module>
    from novaclient import client
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 34, in <module>
    from oslo.utils import netutils
  File "/usr/local/lib/python2.7/dist-packages/oslo/utils/netutils.py", line 78, in <module>
    class _ModifiedSplitResult(parse.SplitResult):
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'SplitResult'
```

**Comment by nikosnikos** [comment]
I have the same problem with duplicity on ubuntu 14.04.

What I've done to make it work :

**Comment by powellchristoph** [comment]
I dealt with the same issue as @nikosnikos . Install the novaclient via system packages resolved the problem.

**Comment by yeasy** [comment]
The same problem happens at the Juno version.
Fix it in the same way as @nikosnikos.

**Comment by geongo** [comment]
For me I had to install both novaclient and glanceclient
$ sudo apt-get install python-novaclient
$ sudo apt-get install python-glanceclient

**Comment by cwillenterprise** [comment]
This can help someone else. To correct the problem I had to remove all the packages installed with pip and reinstall all the packages using the package manager. 

Test the module by importing in the python shell.
