### ISSUE TITLE
parse.py string creation error

### ISSUE THREAD

**Issue by Bobspadger** [pycontribs/pyrax#565]
I've just installed the latest version of pyrax on python3 (I did have the previous release but don't have the versions number to hand!)

My code did work to upload but is now broken.

The error I am getting is:

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 2357, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1777, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "/Users/alexhellier/Documents/git/web_assets/playground/__init__.py", line 42, in <module>
    main()
  File "/Users/alexhellier/Documents/git/web_assets/playground/__init__.py", line 32, in main
    upload = rs.upload_item('WebAssets', file)
  File "/Users/alexhellier/Documents/git/web_assets/playground/rackspace.py", line 37, in upload_item
    rsContainer = cf.get_container(container)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyrax/object_storage.py", line 2250, in get
    item = super(StorageClient, self).get(item)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyrax/client.py", line 98, in get
    return self._manager.get(item)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyrax/object_storage.py", line 127, in wrapped
    return fnc(self, container, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyrax/object_storage.py", line 816, in get
    return Container(self, data, loaded=False)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyrax/object_storage.py", line 161, in __init__
    super(Container, self).__init__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyrax/resource.py", line 52, in __init__
    self._add_details(info)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyrax/resource.py", line 75, in _add_details
    setattr(self, key, val)
TypeError: attribute name must be string, not 'bytes'
```

I think I've traced this to `parse.py`

Line 688
`string = string.encode(encoding, errors)`

This is returning `string = {bytes}b'/MyContainer`

and chucking the error above.

Is this something that has changed 

I am 100% sending in the items as strings

**Comment by Bobspadger** [comment]
I've just noticed the python2.7 only bit on the front page - this may be my error :(

**Comment by Bobspadger** [comment]
If I run the same code via 2.7.10 (all same module versions) the code works and files upload.

The repo seems to have conflicting info on Python3 compatibility , frontpage says 2.7 only, readme and changelog show python3?

**Comment by briancurtin** [comment]
There may have been a few changes here or there to support python3 but pyrax only works on 2.x. We're working on a library to replace pyrax (https://wiki.openstack.org/wiki/SDK-Development/PythonOpenStackSDK, https://pypi.python.org/pypi/python-openstacksdk) and that one works both on 2 and 3. We will be announcing a deprecation plan for pyrax fairly soon as that library nears its 1.0 release.

**Comment by Bobspadger** [comment]
ah excellent, thanks for letting me know :-)

Is the openstack sdk a currently useable solution for doing basic cloudfiles access ? (uploads / downloads etc)

Also - is it a drop in replacement or are there significant differences ? 
I may decide to start my project with the new openstack python code knowing its both 2 and 3 compatible.

Thanks again :)

Alex

**Comment by briancurtin** [comment]
We're still working out some bugs in the object_store code (aka Cloud Files) but that's mostly around metadata, I think. We've fixed a lot of things that haven't been released yet, but we're preparing to do a release very soon. I'll get back to you here with an update.

**Comment by EdLeafe** [comment]
Any idea of a time frame more specific than "very soon"? I've had a few people ask me, but as I no longer maintain pyrax, I don't have a clue. Also, are there plans to have a way to migrate pyrax code to the new OpenStack Python SDK code, or will that require a rewrite?

**Comment by briancurtin** [comment]
I'm working on a better announcement for the deprecation and 1.0 plan, but the next release (0.6) is probably very soon as in a few days, but that's not the big one. There will be no migration - pyrax will just stay as is and go through a cycle of deprecation and only receive security fixes, and then it'll be entirely unsupported.

**Comment by jaraco** [comment]
I've encountered this issue as well, when simply invoking `dns.list()` per the [cloud dns docs](https://github.com/rackspace/pyrax/blob/master/docs/cloud_dns.md).

**Comment by jaraco** [comment]
[This code](https://github.com/rackspace/pyrax/blob/master/pyrax/resource.py#L71-L74) is highly suspect, converting text to bytes and from bytes to text. Generally speaking, it's bad form to perform inverse conversions on an object.

I've found that by disabling that first `if` clause, the error no longer occurs on Python 3.

**Comment by jaraco** [comment]
I added a PR #608 to fix the issue.

**Comment by HQJaTu** [comment]
Please merge the PR #608. Given Python 2 EOL, I'd rather not use it for anything. Pyrax doesn't work at all with my Python 3.

**Comment by jaraco** [comment]
This issue still exists.

```
Successfully installed Babel-2.8.0 PrettyTable-0.7.2 PyYAML-5.3.1 argparse-1.4.0 certifi-2019.11.28 chardet-3.0.4 debtcollector-2.0.0 idna-2.9 importlib-metadata-1.5.0 ip-associations-python-novaclient-ext-0.2 iso8601-0.1.12 keyring-21.2.0 keystoneauth1-3.18.0 mock-4.0.2 msgpack-1.0.0 netaddr-0.7.19 netifaces-0.10.9 os-diskconfig-python-novaclient-ext-0.1.3 os-networksv2-python-novaclient-ext-0.26 os-service-types-1.7.0 os-virtual-interfacesv2-python-novaclient-ext-0.20 oslo.config-8.0.1 oslo.i18n-4.0.0 oslo.serialization-3.1.0 oslo.utils-4.1.0 pbr-1.10.0 pyparsing-2.4.6 pyrax-1.9.8 python-keystoneclient-3.22.0 python-novaclient-2.27.0 pytz-2019.3 rackspace-auth-openstack-1.3 rackspace-novaclient-2.1 rax-default-network-flags-python-novaclient-ext-0.4.0 rax-scheduled-images-python-novaclient-ext-0.3.1 requests-2.23.0 rfc3986-1.3.2 simplejson-3.17.0 six-1.14.0 stevedore-1.32.0 urllib3-1.25.8 wrapt-1.12.1 zipp-3.1.0
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrax
>>> pyrax.set_setting('identity_type', 'rackspace')
>>> import keyring
>>> pyrax.set_credentials('jaraco', keyring.get_password('Rackspace', 'jaraco'))
>>> domain = pyrax.cloud_dns.find(name='jaraco.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-uef0v1st/pyrax/client.py", line 118, in find
    return self._manager.find(**kwargs)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-uef0v1st/pyrax/manager.py", line 265, in find
    matches = self.findall(**kwargs)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-uef0v1st/pyrax/clouddns.py", line 601, in findall
    matches = self._list(uri, list_all=True)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-uef0v1st/pyrax/clouddns.py", line 398, in _list
    for res in data if res]
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-uef0v1st/pyrax/clouddns.py", line 398, in <listcomp>
    for res in data if res]
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-uef0v1st/pyrax/resource.py", line 52, in __init__
    self._add_details(info)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-uef0v1st/pyrax/resource.py", line 75, in _add_details
    setattr(self, key, val)
TypeError: attribute name must be string, not 'bytes'
```

It's annoying that this library is both deprecated and [advertised](https://developer.rackspace.com/docs/cloud-dns/quickstart/?lang=python).

**Comment by HQJaTu** [comment]
> This issue still exists.
> ...
> It's annoying that this library is both deprecated and [advertised](https://developer.rackspace.com/docs/cloud-dns/quickstart/?lang=python).

Exactly.
As I need DNS API myself, I'm maintaining https://github.com/HQJaTu/pyrax

**Comment by rax-rstark** [comment]
For what it's worth, I have alerted the Rackspace document ion team to this discrepancy in hopes they update the page to no longer reference pyrax solutions.

**Comment by HQJaTu** [comment]
> For what it's worth, I have alerted the Rackspace document ion team to this discrepancy in hopes they update the page to no longer reference pyrax solutions.

Thanks. I'm sure they already know. What they haven't done is released a supported library which would have support for their cloud-DNS -product.
