### ISSUE TITLE
rackspacesdk doesn't work

### ISSUE THREAD

**Issue by jaraco** [pycontribs/pyrax#654]
As pyrax is deprecated in favor of rackspacesdk, I tried using rackspace SDK, and after working around a couple of build issues, I ran into a new issue with rackspace SDK.

```
~ $ pip-run -q --use-pep517 rackspacesdk setuptools -- -c "from rackspace import connection"                                                                              
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-l0k22gpq/rackspace/connection.py", line 16, in <module>
    from rackspace import profile as _profile
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-l0k22gpq/rackspace/profile.py", line 13, in <module>
    from openstack import profile
ImportError: cannot import name 'profile' from 'openstack' (/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-l0k22gpq/openstack/__init__.py)

```

Following the PyPI project to its homepage led me to Rackspace's API page, which led me here. I'm not even sure where the source code is for rackspacesdk. Please let me know if there's a better place where I can report issues with rackspacesdk.

**Comment by ssbarnea** [comment]
That is the place but read https://github.com/pycontribs/pyrax/issues/630 -- mainly, it will need bit of nurturing.

**Comment by wmcbroomd2d** [comment]
In case others are looking for a workaround for the `ImportError: cannot import name 'profile' from 'openstack'` error. The problem is that the `rackspacesdk` v.0.7.5 app has requirements setup for `openstacksdk` (<=1.0,>=0.9.9). But in `openstacksdk` v.0.18.0 the `profile` class was changed causing it to be incompatible. So you need to manually install `openstacksdk==0.17.3` to get the latest compatible version that works with `rackspacesdk`.
